# Generated by Django 3.1.7 on 2021-03-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api', models.CharField(max_length=1000)),
                ('factory_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=20)),
                ('liquidity', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.exchange')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_token', to='walletview.token')),
                ('token0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_token0', to='walletview.token')),
                ('token1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_token1', to='walletview.token')),
            ],
        ),
    ]
