# Generated by Django 3.1.7 on 2021-03-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidityvalue',
            old_name='value',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='liquidityvalue',
            name='token',
        ),
        migrations.CreateModel(
            name='WalletLiquidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('fetched', models.DateTimeField(auto_now_add=True, verbose_name='fetched')),
                ('liquidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.liquiditytoken')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.wallet')),
            ],
        ),
    ]
