# Generated by Django 3.1.7 on 2021-03-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletview', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='owner',
        ),
    ]
