# Generated by Django 3.1.7 on 2021-03-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletview', '0002_auto_20210325_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='liquidityvalue',
            name='fetched',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fetched'),
        ),
        migrations.AlterField(
            model_name='tokenvalue',
            name='fetched',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fetched'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='fetched',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fetched'),
        ),
        migrations.AlterField(
            model_name='wallettoken',
            name='fetched',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fetched'),
        ),
    ]
