# Generated by Django 3.1.7 on 2021-03-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletview', '0003_remove_wallet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=250)),
                ('decimals', models.IntegerField()),
                ('fetched', models.DateTimeField(verbose_name='fetched')),
                ('liquidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.liquiditytoken')),
            ],
        ),
        migrations.CreateModel(
            name='TokenValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('fetched', models.DateTimeField(verbose_name='fetched')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.exchange')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.token')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('fetched', models.DateTimeField(verbose_name='fetched')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.token')),
            ],
        ),
    ]
