# Generated by Django 3.1.7 on 2021-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletview', '0003_watchwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='symbol',
            field=models.CharField(max_length=255),
        ),
    ]
