# Generated by Django 3.1.7 on 2021-03-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api', models.CharField(max_length=1000)),
                ('factory_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=20)),
                ('liquidity', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityToken',
            fields=[
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='walletview.token')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.exchange')),
                ('token0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_token0', to='walletview.token')),
                ('token1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_token1', to='walletview.token')),
            ],
        ),
        migrations.CreateModel(
            name='WalletToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=250)),
                ('decimals', models.IntegerField()),
                ('fetched', models.DateTimeField(auto_now_add=True, verbose_name='fetched')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xdai_balance', models.CharField(max_length=250)),
                ('fetched', models.DateTimeField(auto_now_add=True, verbose_name='fetched')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TokenValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('fetched', models.DateTimeField(auto_now_add=True, verbose_name='fetched')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.exchange')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.token')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('fetched', models.DateTimeField(auto_now_add=True, verbose_name='fetched')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.token')),
                ('liquidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletview.liquiditytoken')),
            ],
        ),
    ]
